# .github/workflows/metrics.yml
name: GitHub Metrics
on:
  # Roda a cada 6 horas e ao fazer push
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu nome de usuário
          user: ZecaBigodinho
          
          # Use o tema cyberpunk
          template: classic
          config_timezone: America/Sao_Paulo
          theme_common: cyberpunk
          
          # Token do GitHub (necessário para stats privadas)
          token: ${{ secrets.METRICS_TOKEN }}

          # Habilita as linguagens
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
